#!/usr/bin/with-contenv bash

# test if we need to run the update scripts
[ "$ADVANCED_DISABLEUPDATES" ] && exit 0
[ "$BASE_APTLIST" ] && APTLIST="$BASE_APTLIST ""$APTLIST"
[ "$APTLIST" ] || exit 0

# run apt-select script to find fastest up to date mirror
cd /tmp || exit
echo "Generating sources.list"
python3 /usr/local/bin/aptselect.d/apt-select.py -t 3 -m up-to-date
mv /tmp/sources.list /etc/apt/sources.list

# check for and install any updates
echo "Updateing Software from apt. Please be patient"
apt-get update
apt-get --only-upgrade install -yqq $APTLIST
